# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: "ngv-iem"
  name: "fbmc-eraa2024-test-1H-Jan"
  scenarios:
    enable: false

fbmc:
  enable: true
  eraa_version: "eraa2024" # 2023 or 2024
  ram_year: 2030
  # the following settings only for 2024, leave empty for eraa2023
  ptdf_year: 2030 # For loading PTDF values
  weather_scenario: "WS29" # For selecting FB Domain
  weather_year: 2030 # For selecting FB Domain

snapshots:
  # TODO define multiple climatic years, being either 1995 2008 or 2009
  start: "2009-01-07"
  end: "2009-01-14"

scenario:
  clusters:
  - all
  planning_horizons:
  - 2030
  # - 2040

tyndp_scenario: NT

clustering:
  temporal:
    resolution_sector: 1H

sector:
  h2_zones_tyndp: false
  co2_sequestration_potential:
    # Values fomr TYNDP 2024 Supply Tool
    2030: 47
    2035: 167
    2040: 344


benchmarking:
  enable: false
