# SPDX-FileCopyrightText: Contributors to Open-TYNDP <https://github.com/open-energy-transition/open-tyndp>
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: "ngv-iem"
  name: "fbmc-test"
  scenarios:
    enable: false

fbmc: true

snapshots:
  # TODO define multiple climatic years, being either 1995 2008 or 2009
  start: "2009-01-01"
  end: "2009-03-01"

scenario:
  clusters:
  - all
  planning_horizons:
  - 2030

tyndp_scenario: NT

clustering:
  temporal:
    resolution_sector: 6H

benchmarking:
  enable: false